// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tfoplibrary.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tfoplibrary.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace executor {
class TFOpKernelDefDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TFOpKernelDef> {
} _TFOpKernelDef_default_instance_;
class TFOpContextDefDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TFOpContextDef> {
} _TFOpContextDef_default_instance_;
class TFOpContextUpdateDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TFOpContextUpdate> {
} _TFOpContextUpdate_default_instance_;

namespace protobuf_tfoplibrary_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpKernelDef, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpKernelDef, graph_def_version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpKernelDef, nodedef_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpKernelDef, cfgproto_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpKernelDef, funcdef_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextDef, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextDef, step_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextDef, frame_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextDef, iter_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextDef, is_input_dead_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextDef, inputs_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextUpdate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextUpdate, is_output_dead_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextUpdate, outputs_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextUpdate, status_code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TFOpContextUpdate, status_msg_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(TFOpKernelDef)},
  { 8, -1, sizeof(TFOpContextDef)},
  { 17, -1, sizeof(TFOpContextUpdate)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_TFOpKernelDef_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_TFOpContextDef_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_TFOpContextUpdate_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "tfoplibrary.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace

void TableStruct::Shutdown() {
  _TFOpKernelDef_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _TFOpContextDef_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _TFOpContextUpdate_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::tensorflow::protobuf_tensorflow_2fcore_2fframework_2fnode_5fdef_2eproto::InitDefaults();
  ::tensorflow::protobuf_tensorflow_2fcore_2fframework_2ffunction_2eproto::InitDefaults();
  ::tensorflow::protobuf_tensorflow_2fcore_2fframework_2ftensor_2eproto::InitDefaults();
  ::tensorflow::protobuf_tensorflow_2fcore_2fprotobuf_2fconfig_2eproto::InitDefaults();
  ::tensorflow::error::protobuf_tensorflow_2fcore_2flib_2fcore_2ferror_5fcodes_2eproto::InitDefaults();
  _TFOpKernelDef_default_instance_.DefaultConstruct();
  _TFOpContextDef_default_instance_.DefaultConstruct();
  _TFOpContextUpdate_default_instance_.DefaultConstruct();
  _TFOpKernelDef_default_instance_.get_mutable()->nodedef_ = const_cast< ::tensorflow::NodeDef*>(
      ::tensorflow::NodeDef::internal_default_instance());
  _TFOpKernelDef_default_instance_.get_mutable()->cfgproto_ = const_cast< ::tensorflow::ConfigProto*>(
      ::tensorflow::ConfigProto::internal_default_instance());
  _TFOpKernelDef_default_instance_.get_mutable()->funcdef_ = const_cast< ::tensorflow::FunctionDefLibrary*>(
      ::tensorflow::FunctionDefLibrary::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\021tfoplibrary.proto\022\010executor\032(tensorflo"
      "w/core/framework/node_def.proto\032(tensorf"
      "low/core/framework/function.proto\032&tenso"
      "rflow/core/framework/tensor.proto\032%tenso"
      "rflow/core/protobuf/config.proto\032*tensor"
      "flow/core/lib/core/error_codes.proto\"\254\001\n"
      "\rTFOpKernelDef\022\031\n\021graph_def_version\030\001 \001("
      "\005\022$\n\007nodedef\030\002 \001(\0132\023.tensorflow.NodeDef\022"
      ")\n\010cfgProto\030\003 \001(\0132\027.tensorflow.ConfigPro"
      "to\022/\n\007funcDef\030\004 \001(\0132\036.tensorflow.Functio"
      "nDefLibrary\"\204\001\n\016TFOpContextDef\022\017\n\007step_i"
      "d\030\001 \001(\003\022\020\n\010frame_id\030\002 \001(\004\022\017\n\007iter_id\030\003 \001"
      "(\003\022\025\n\ris_input_dead\030\004 \001(\010\022\'\n\006inputs\030\005 \003("
      "\0132\027.tensorflow.TensorProto\"\226\001\n\021TFOpConte"
      "xtUpdate\022\026\n\016is_output_dead\030\001 \001(\010\022(\n\007outp"
      "uts\030\002 \003(\0132\027.tensorflow.TensorProto\022+\n\013st"
      "atus_code\030\004 \001(\0162\026.tensorflow.error.Code\022"
      "\022\n\nstatus_msg\030\005 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 707);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tfoplibrary.proto", &protobuf_RegisterTypes);
  ::tensorflow::protobuf_tensorflow_2fcore_2fframework_2fnode_5fdef_2eproto::AddDescriptors();
  ::tensorflow::protobuf_tensorflow_2fcore_2fframework_2ffunction_2eproto::AddDescriptors();
  ::tensorflow::protobuf_tensorflow_2fcore_2fframework_2ftensor_2eproto::AddDescriptors();
  ::tensorflow::protobuf_tensorflow_2fcore_2fprotobuf_2fconfig_2eproto::AddDescriptors();
  ::tensorflow::error::protobuf_tensorflow_2fcore_2flib_2fcore_2ferror_5fcodes_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_tfoplibrary_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TFOpKernelDef::kGraphDefVersionFieldNumber;
const int TFOpKernelDef::kNodedefFieldNumber;
const int TFOpKernelDef::kCfgProtoFieldNumber;
const int TFOpKernelDef::kFuncDefFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TFOpKernelDef::TFOpKernelDef()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tfoplibrary_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:executor.TFOpKernelDef)
}
TFOpKernelDef::TFOpKernelDef(const TFOpKernelDef& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_nodedef()) {
    nodedef_ = new ::tensorflow::NodeDef(*from.nodedef_);
  } else {
    nodedef_ = NULL;
  }
  if (from.has_cfgproto()) {
    cfgproto_ = new ::tensorflow::ConfigProto(*from.cfgproto_);
  } else {
    cfgproto_ = NULL;
  }
  if (from.has_funcdef()) {
    funcdef_ = new ::tensorflow::FunctionDefLibrary(*from.funcdef_);
  } else {
    funcdef_ = NULL;
  }
  graph_def_version_ = from.graph_def_version_;
  // @@protoc_insertion_point(copy_constructor:executor.TFOpKernelDef)
}

void TFOpKernelDef::SharedCtor() {
  ::memset(&nodedef_, 0, reinterpret_cast<char*>(&graph_def_version_) -
    reinterpret_cast<char*>(&nodedef_) + sizeof(graph_def_version_));
  _cached_size_ = 0;
}

TFOpKernelDef::~TFOpKernelDef() {
  // @@protoc_insertion_point(destructor:executor.TFOpKernelDef)
  SharedDtor();
}

void TFOpKernelDef::SharedDtor() {
  if (this != internal_default_instance()) {
    delete nodedef_;
  }
  if (this != internal_default_instance()) {
    delete cfgproto_;
  }
  if (this != internal_default_instance()) {
    delete funcdef_;
  }
}

void TFOpKernelDef::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TFOpKernelDef::descriptor() {
  protobuf_tfoplibrary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tfoplibrary_2eproto::file_level_metadata[0].descriptor;
}

const TFOpKernelDef& TFOpKernelDef::default_instance() {
  protobuf_tfoplibrary_2eproto::InitDefaults();
  return *internal_default_instance();
}

TFOpKernelDef* TFOpKernelDef::New(::google::protobuf::Arena* arena) const {
  TFOpKernelDef* n = new TFOpKernelDef;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TFOpKernelDef::Clear() {
// @@protoc_insertion_point(message_clear_start:executor.TFOpKernelDef)
  if (GetArenaNoVirtual() == NULL && nodedef_ != NULL) {
    delete nodedef_;
  }
  nodedef_ = NULL;
  if (GetArenaNoVirtual() == NULL && cfgproto_ != NULL) {
    delete cfgproto_;
  }
  cfgproto_ = NULL;
  if (GetArenaNoVirtual() == NULL && funcdef_ != NULL) {
    delete funcdef_;
  }
  funcdef_ = NULL;
  graph_def_version_ = 0;
}

bool TFOpKernelDef::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:executor.TFOpKernelDef)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 graph_def_version = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &graph_def_version_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tensorflow.NodeDef nodedef = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_nodedef()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tensorflow.ConfigProto cfgProto = 3;
      case 3: {
        if (tag == 26u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_cfgproto()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tensorflow.FunctionDefLibrary funcDef = 4;
      case 4: {
        if (tag == 34u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_funcdef()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:executor.TFOpKernelDef)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:executor.TFOpKernelDef)
  return false;
#undef DO_
}

void TFOpKernelDef::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:executor.TFOpKernelDef)
  // int32 graph_def_version = 1;
  if (this->graph_def_version() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->graph_def_version(), output);
  }

  // .tensorflow.NodeDef nodedef = 2;
  if (this->has_nodedef()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->nodedef_, output);
  }

  // .tensorflow.ConfigProto cfgProto = 3;
  if (this->has_cfgproto()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->cfgproto_, output);
  }

  // .tensorflow.FunctionDefLibrary funcDef = 4;
  if (this->has_funcdef()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->funcdef_, output);
  }

  // @@protoc_insertion_point(serialize_end:executor.TFOpKernelDef)
}

::google::protobuf::uint8* TFOpKernelDef::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:executor.TFOpKernelDef)
  // int32 graph_def_version = 1;
  if (this->graph_def_version() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->graph_def_version(), target);
  }

  // .tensorflow.NodeDef nodedef = 2;
  if (this->has_nodedef()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->nodedef_, false, target);
  }

  // .tensorflow.ConfigProto cfgProto = 3;
  if (this->has_cfgproto()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->cfgproto_, false, target);
  }

  // .tensorflow.FunctionDefLibrary funcDef = 4;
  if (this->has_funcdef()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->funcdef_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:executor.TFOpKernelDef)
  return target;
}

size_t TFOpKernelDef::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:executor.TFOpKernelDef)
  size_t total_size = 0;

  // .tensorflow.NodeDef nodedef = 2;
  if (this->has_nodedef()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->nodedef_);
  }

  // .tensorflow.ConfigProto cfgProto = 3;
  if (this->has_cfgproto()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->cfgproto_);
  }

  // .tensorflow.FunctionDefLibrary funcDef = 4;
  if (this->has_funcdef()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->funcdef_);
  }

  // int32 graph_def_version = 1;
  if (this->graph_def_version() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->graph_def_version());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TFOpKernelDef::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:executor.TFOpKernelDef)
  GOOGLE_DCHECK_NE(&from, this);
  const TFOpKernelDef* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TFOpKernelDef>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:executor.TFOpKernelDef)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:executor.TFOpKernelDef)
    MergeFrom(*source);
  }
}

void TFOpKernelDef::MergeFrom(const TFOpKernelDef& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:executor.TFOpKernelDef)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_nodedef()) {
    mutable_nodedef()->::tensorflow::NodeDef::MergeFrom(from.nodedef());
  }
  if (from.has_cfgproto()) {
    mutable_cfgproto()->::tensorflow::ConfigProto::MergeFrom(from.cfgproto());
  }
  if (from.has_funcdef()) {
    mutable_funcdef()->::tensorflow::FunctionDefLibrary::MergeFrom(from.funcdef());
  }
  if (from.graph_def_version() != 0) {
    set_graph_def_version(from.graph_def_version());
  }
}

void TFOpKernelDef::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:executor.TFOpKernelDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TFOpKernelDef::CopyFrom(const TFOpKernelDef& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:executor.TFOpKernelDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TFOpKernelDef::IsInitialized() const {
  return true;
}

void TFOpKernelDef::Swap(TFOpKernelDef* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TFOpKernelDef::InternalSwap(TFOpKernelDef* other) {
  std::swap(nodedef_, other->nodedef_);
  std::swap(cfgproto_, other->cfgproto_);
  std::swap(funcdef_, other->funcdef_);
  std::swap(graph_def_version_, other->graph_def_version_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TFOpKernelDef::GetMetadata() const {
  protobuf_tfoplibrary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tfoplibrary_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TFOpKernelDef

// int32 graph_def_version = 1;
void TFOpKernelDef::clear_graph_def_version() {
  graph_def_version_ = 0;
}
::google::protobuf::int32 TFOpKernelDef::graph_def_version() const {
  // @@protoc_insertion_point(field_get:executor.TFOpKernelDef.graph_def_version)
  return graph_def_version_;
}
void TFOpKernelDef::set_graph_def_version(::google::protobuf::int32 value) {
  
  graph_def_version_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpKernelDef.graph_def_version)
}

// .tensorflow.NodeDef nodedef = 2;
bool TFOpKernelDef::has_nodedef() const {
  return this != internal_default_instance() && nodedef_ != NULL;
}
void TFOpKernelDef::clear_nodedef() {
  if (GetArenaNoVirtual() == NULL && nodedef_ != NULL) delete nodedef_;
  nodedef_ = NULL;
}
const ::tensorflow::NodeDef& TFOpKernelDef::nodedef() const {
  // @@protoc_insertion_point(field_get:executor.TFOpKernelDef.nodedef)
  return nodedef_ != NULL ? *nodedef_
                         : *::tensorflow::NodeDef::internal_default_instance();
}
::tensorflow::NodeDef* TFOpKernelDef::mutable_nodedef() {
  
  if (nodedef_ == NULL) {
    nodedef_ = new ::tensorflow::NodeDef;
  }
  // @@protoc_insertion_point(field_mutable:executor.TFOpKernelDef.nodedef)
  return nodedef_;
}
::tensorflow::NodeDef* TFOpKernelDef::release_nodedef() {
  // @@protoc_insertion_point(field_release:executor.TFOpKernelDef.nodedef)
  
  ::tensorflow::NodeDef* temp = nodedef_;
  nodedef_ = NULL;
  return temp;
}
void TFOpKernelDef::set_allocated_nodedef(::tensorflow::NodeDef* nodedef) {
  delete nodedef_;
  if (nodedef != NULL && nodedef->GetArena() != NULL) {
    ::tensorflow::NodeDef* new_nodedef = new ::tensorflow::NodeDef;
    new_nodedef->CopyFrom(*nodedef);
    nodedef = new_nodedef;
  }
  nodedef_ = nodedef;
  if (nodedef) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:executor.TFOpKernelDef.nodedef)
}

// .tensorflow.ConfigProto cfgProto = 3;
bool TFOpKernelDef::has_cfgproto() const {
  return this != internal_default_instance() && cfgproto_ != NULL;
}
void TFOpKernelDef::clear_cfgproto() {
  if (GetArenaNoVirtual() == NULL && cfgproto_ != NULL) delete cfgproto_;
  cfgproto_ = NULL;
}
const ::tensorflow::ConfigProto& TFOpKernelDef::cfgproto() const {
  // @@protoc_insertion_point(field_get:executor.TFOpKernelDef.cfgProto)
  return cfgproto_ != NULL ? *cfgproto_
                         : *::tensorflow::ConfigProto::internal_default_instance();
}
::tensorflow::ConfigProto* TFOpKernelDef::mutable_cfgproto() {
  
  if (cfgproto_ == NULL) {
    cfgproto_ = new ::tensorflow::ConfigProto;
  }
  // @@protoc_insertion_point(field_mutable:executor.TFOpKernelDef.cfgProto)
  return cfgproto_;
}
::tensorflow::ConfigProto* TFOpKernelDef::release_cfgproto() {
  // @@protoc_insertion_point(field_release:executor.TFOpKernelDef.cfgProto)
  
  ::tensorflow::ConfigProto* temp = cfgproto_;
  cfgproto_ = NULL;
  return temp;
}
void TFOpKernelDef::set_allocated_cfgproto(::tensorflow::ConfigProto* cfgproto) {
  delete cfgproto_;
  if (cfgproto != NULL && cfgproto->GetArena() != NULL) {
    ::tensorflow::ConfigProto* new_cfgproto = new ::tensorflow::ConfigProto;
    new_cfgproto->CopyFrom(*cfgproto);
    cfgproto = new_cfgproto;
  }
  cfgproto_ = cfgproto;
  if (cfgproto) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:executor.TFOpKernelDef.cfgProto)
}

// .tensorflow.FunctionDefLibrary funcDef = 4;
bool TFOpKernelDef::has_funcdef() const {
  return this != internal_default_instance() && funcdef_ != NULL;
}
void TFOpKernelDef::clear_funcdef() {
  if (GetArenaNoVirtual() == NULL && funcdef_ != NULL) delete funcdef_;
  funcdef_ = NULL;
}
const ::tensorflow::FunctionDefLibrary& TFOpKernelDef::funcdef() const {
  // @@protoc_insertion_point(field_get:executor.TFOpKernelDef.funcDef)
  return funcdef_ != NULL ? *funcdef_
                         : *::tensorflow::FunctionDefLibrary::internal_default_instance();
}
::tensorflow::FunctionDefLibrary* TFOpKernelDef::mutable_funcdef() {
  
  if (funcdef_ == NULL) {
    funcdef_ = new ::tensorflow::FunctionDefLibrary;
  }
  // @@protoc_insertion_point(field_mutable:executor.TFOpKernelDef.funcDef)
  return funcdef_;
}
::tensorflow::FunctionDefLibrary* TFOpKernelDef::release_funcdef() {
  // @@protoc_insertion_point(field_release:executor.TFOpKernelDef.funcDef)
  
  ::tensorflow::FunctionDefLibrary* temp = funcdef_;
  funcdef_ = NULL;
  return temp;
}
void TFOpKernelDef::set_allocated_funcdef(::tensorflow::FunctionDefLibrary* funcdef) {
  delete funcdef_;
  if (funcdef != NULL && funcdef->GetArena() != NULL) {
    ::tensorflow::FunctionDefLibrary* new_funcdef = new ::tensorflow::FunctionDefLibrary;
    new_funcdef->CopyFrom(*funcdef);
    funcdef = new_funcdef;
  }
  funcdef_ = funcdef;
  if (funcdef) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:executor.TFOpKernelDef.funcDef)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TFOpContextDef::kStepIdFieldNumber;
const int TFOpContextDef::kFrameIdFieldNumber;
const int TFOpContextDef::kIterIdFieldNumber;
const int TFOpContextDef::kIsInputDeadFieldNumber;
const int TFOpContextDef::kInputsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TFOpContextDef::TFOpContextDef()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tfoplibrary_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:executor.TFOpContextDef)
}
TFOpContextDef::TFOpContextDef(const TFOpContextDef& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      inputs_(from.inputs_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&step_id_, &from.step_id_,
    reinterpret_cast<char*>(&is_input_dead_) -
    reinterpret_cast<char*>(&step_id_) + sizeof(is_input_dead_));
  // @@protoc_insertion_point(copy_constructor:executor.TFOpContextDef)
}

void TFOpContextDef::SharedCtor() {
  ::memset(&step_id_, 0, reinterpret_cast<char*>(&is_input_dead_) -
    reinterpret_cast<char*>(&step_id_) + sizeof(is_input_dead_));
  _cached_size_ = 0;
}

TFOpContextDef::~TFOpContextDef() {
  // @@protoc_insertion_point(destructor:executor.TFOpContextDef)
  SharedDtor();
}

void TFOpContextDef::SharedDtor() {
}

void TFOpContextDef::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TFOpContextDef::descriptor() {
  protobuf_tfoplibrary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tfoplibrary_2eproto::file_level_metadata[1].descriptor;
}

const TFOpContextDef& TFOpContextDef::default_instance() {
  protobuf_tfoplibrary_2eproto::InitDefaults();
  return *internal_default_instance();
}

TFOpContextDef* TFOpContextDef::New(::google::protobuf::Arena* arena) const {
  TFOpContextDef* n = new TFOpContextDef;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TFOpContextDef::Clear() {
// @@protoc_insertion_point(message_clear_start:executor.TFOpContextDef)
  inputs_.Clear();
  ::memset(&step_id_, 0, reinterpret_cast<char*>(&is_input_dead_) -
    reinterpret_cast<char*>(&step_id_) + sizeof(is_input_dead_));
}

bool TFOpContextDef::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:executor.TFOpContextDef)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 step_id = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &step_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 frame_id = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &frame_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 iter_id = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &iter_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool is_input_dead = 4;
      case 4: {
        if (tag == 32u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_input_dead_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .tensorflow.TensorProto inputs = 5;
      case 5: {
        if (tag == 42u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_inputs()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:executor.TFOpContextDef)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:executor.TFOpContextDef)
  return false;
#undef DO_
}

void TFOpContextDef::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:executor.TFOpContextDef)
  // int64 step_id = 1;
  if (this->step_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->step_id(), output);
  }

  // uint64 frame_id = 2;
  if (this->frame_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->frame_id(), output);
  }

  // int64 iter_id = 3;
  if (this->iter_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->iter_id(), output);
  }

  // bool is_input_dead = 4;
  if (this->is_input_dead() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->is_input_dead(), output);
  }

  // repeated .tensorflow.TensorProto inputs = 5;
  for (unsigned int i = 0, n = this->inputs_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->inputs(i), output);
  }

  // @@protoc_insertion_point(serialize_end:executor.TFOpContextDef)
}

::google::protobuf::uint8* TFOpContextDef::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:executor.TFOpContextDef)
  // int64 step_id = 1;
  if (this->step_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->step_id(), target);
  }

  // uint64 frame_id = 2;
  if (this->frame_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->frame_id(), target);
  }

  // int64 iter_id = 3;
  if (this->iter_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->iter_id(), target);
  }

  // bool is_input_dead = 4;
  if (this->is_input_dead() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->is_input_dead(), target);
  }

  // repeated .tensorflow.TensorProto inputs = 5;
  for (unsigned int i = 0, n = this->inputs_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, this->inputs(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:executor.TFOpContextDef)
  return target;
}

size_t TFOpContextDef::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:executor.TFOpContextDef)
  size_t total_size = 0;

  // repeated .tensorflow.TensorProto inputs = 5;
  {
    unsigned int count = this->inputs_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->inputs(i));
    }
  }

  // int64 step_id = 1;
  if (this->step_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->step_id());
  }

  // uint64 frame_id = 2;
  if (this->frame_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->frame_id());
  }

  // int64 iter_id = 3;
  if (this->iter_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->iter_id());
  }

  // bool is_input_dead = 4;
  if (this->is_input_dead() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TFOpContextDef::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:executor.TFOpContextDef)
  GOOGLE_DCHECK_NE(&from, this);
  const TFOpContextDef* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TFOpContextDef>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:executor.TFOpContextDef)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:executor.TFOpContextDef)
    MergeFrom(*source);
  }
}

void TFOpContextDef::MergeFrom(const TFOpContextDef& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:executor.TFOpContextDef)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  inputs_.MergeFrom(from.inputs_);
  if (from.step_id() != 0) {
    set_step_id(from.step_id());
  }
  if (from.frame_id() != 0) {
    set_frame_id(from.frame_id());
  }
  if (from.iter_id() != 0) {
    set_iter_id(from.iter_id());
  }
  if (from.is_input_dead() != 0) {
    set_is_input_dead(from.is_input_dead());
  }
}

void TFOpContextDef::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:executor.TFOpContextDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TFOpContextDef::CopyFrom(const TFOpContextDef& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:executor.TFOpContextDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TFOpContextDef::IsInitialized() const {
  return true;
}

void TFOpContextDef::Swap(TFOpContextDef* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TFOpContextDef::InternalSwap(TFOpContextDef* other) {
  inputs_.UnsafeArenaSwap(&other->inputs_);
  std::swap(step_id_, other->step_id_);
  std::swap(frame_id_, other->frame_id_);
  std::swap(iter_id_, other->iter_id_);
  std::swap(is_input_dead_, other->is_input_dead_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TFOpContextDef::GetMetadata() const {
  protobuf_tfoplibrary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tfoplibrary_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TFOpContextDef

// int64 step_id = 1;
void TFOpContextDef::clear_step_id() {
  step_id_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 TFOpContextDef::step_id() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.step_id)
  return step_id_;
}
void TFOpContextDef::set_step_id(::google::protobuf::int64 value) {
  
  step_id_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.step_id)
}

// uint64 frame_id = 2;
void TFOpContextDef::clear_frame_id() {
  frame_id_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 TFOpContextDef::frame_id() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.frame_id)
  return frame_id_;
}
void TFOpContextDef::set_frame_id(::google::protobuf::uint64 value) {
  
  frame_id_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.frame_id)
}

// int64 iter_id = 3;
void TFOpContextDef::clear_iter_id() {
  iter_id_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 TFOpContextDef::iter_id() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.iter_id)
  return iter_id_;
}
void TFOpContextDef::set_iter_id(::google::protobuf::int64 value) {
  
  iter_id_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.iter_id)
}

// bool is_input_dead = 4;
void TFOpContextDef::clear_is_input_dead() {
  is_input_dead_ = false;
}
bool TFOpContextDef::is_input_dead() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.is_input_dead)
  return is_input_dead_;
}
void TFOpContextDef::set_is_input_dead(bool value) {
  
  is_input_dead_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.is_input_dead)
}

// repeated .tensorflow.TensorProto inputs = 5;
int TFOpContextDef::inputs_size() const {
  return inputs_.size();
}
void TFOpContextDef::clear_inputs() {
  inputs_.Clear();
}
const ::tensorflow::TensorProto& TFOpContextDef::inputs(int index) const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.inputs)
  return inputs_.Get(index);
}
::tensorflow::TensorProto* TFOpContextDef::mutable_inputs(int index) {
  // @@protoc_insertion_point(field_mutable:executor.TFOpContextDef.inputs)
  return inputs_.Mutable(index);
}
::tensorflow::TensorProto* TFOpContextDef::add_inputs() {
  // @@protoc_insertion_point(field_add:executor.TFOpContextDef.inputs)
  return inputs_.Add();
}
::google::protobuf::RepeatedPtrField< ::tensorflow::TensorProto >*
TFOpContextDef::mutable_inputs() {
  // @@protoc_insertion_point(field_mutable_list:executor.TFOpContextDef.inputs)
  return &inputs_;
}
const ::google::protobuf::RepeatedPtrField< ::tensorflow::TensorProto >&
TFOpContextDef::inputs() const {
  // @@protoc_insertion_point(field_list:executor.TFOpContextDef.inputs)
  return inputs_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TFOpContextUpdate::kIsOutputDeadFieldNumber;
const int TFOpContextUpdate::kOutputsFieldNumber;
const int TFOpContextUpdate::kStatusCodeFieldNumber;
const int TFOpContextUpdate::kStatusMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TFOpContextUpdate::TFOpContextUpdate()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tfoplibrary_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:executor.TFOpContextUpdate)
}
TFOpContextUpdate::TFOpContextUpdate(const TFOpContextUpdate& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      outputs_(from.outputs_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  status_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.status_msg().size() > 0) {
    status_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_msg_);
  }
  ::memcpy(&is_output_dead_, &from.is_output_dead_,
    reinterpret_cast<char*>(&status_code_) -
    reinterpret_cast<char*>(&is_output_dead_) + sizeof(status_code_));
  // @@protoc_insertion_point(copy_constructor:executor.TFOpContextUpdate)
}

void TFOpContextUpdate::SharedCtor() {
  status_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&is_output_dead_, 0, reinterpret_cast<char*>(&status_code_) -
    reinterpret_cast<char*>(&is_output_dead_) + sizeof(status_code_));
  _cached_size_ = 0;
}

TFOpContextUpdate::~TFOpContextUpdate() {
  // @@protoc_insertion_point(destructor:executor.TFOpContextUpdate)
  SharedDtor();
}

void TFOpContextUpdate::SharedDtor() {
  status_msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void TFOpContextUpdate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TFOpContextUpdate::descriptor() {
  protobuf_tfoplibrary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tfoplibrary_2eproto::file_level_metadata[2].descriptor;
}

const TFOpContextUpdate& TFOpContextUpdate::default_instance() {
  protobuf_tfoplibrary_2eproto::InitDefaults();
  return *internal_default_instance();
}

TFOpContextUpdate* TFOpContextUpdate::New(::google::protobuf::Arena* arena) const {
  TFOpContextUpdate* n = new TFOpContextUpdate;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TFOpContextUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:executor.TFOpContextUpdate)
  outputs_.Clear();
  status_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&is_output_dead_, 0, reinterpret_cast<char*>(&status_code_) -
    reinterpret_cast<char*>(&is_output_dead_) + sizeof(status_code_));
}

bool TFOpContextUpdate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:executor.TFOpContextUpdate)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool is_output_dead = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_output_dead_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .tensorflow.TensorProto outputs = 2;
      case 2: {
        if (tag == 18u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_outputs()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // .tensorflow.error.Code status_code = 4;
      case 4: {
        if (tag == 32u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_status_code(static_cast< ::tensorflow::error::Code >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string status_msg = 5;
      case 5: {
        if (tag == 42u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_status_msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->status_msg().data(), this->status_msg().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "executor.TFOpContextUpdate.status_msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:executor.TFOpContextUpdate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:executor.TFOpContextUpdate)
  return false;
#undef DO_
}

void TFOpContextUpdate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:executor.TFOpContextUpdate)
  // bool is_output_dead = 1;
  if (this->is_output_dead() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->is_output_dead(), output);
  }

  // repeated .tensorflow.TensorProto outputs = 2;
  for (unsigned int i = 0, n = this->outputs_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->outputs(i), output);
  }

  // .tensorflow.error.Code status_code = 4;
  if (this->status_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->status_code(), output);
  }

  // string status_msg = 5;
  if (this->status_msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status_msg().data(), this->status_msg().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "executor.TFOpContextUpdate.status_msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->status_msg(), output);
  }

  // @@protoc_insertion_point(serialize_end:executor.TFOpContextUpdate)
}

::google::protobuf::uint8* TFOpContextUpdate::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:executor.TFOpContextUpdate)
  // bool is_output_dead = 1;
  if (this->is_output_dead() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->is_output_dead(), target);
  }

  // repeated .tensorflow.TensorProto outputs = 2;
  for (unsigned int i = 0, n = this->outputs_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->outputs(i), false, target);
  }

  // .tensorflow.error.Code status_code = 4;
  if (this->status_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->status_code(), target);
  }

  // string status_msg = 5;
  if (this->status_msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status_msg().data(), this->status_msg().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "executor.TFOpContextUpdate.status_msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->status_msg(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:executor.TFOpContextUpdate)
  return target;
}

size_t TFOpContextUpdate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:executor.TFOpContextUpdate)
  size_t total_size = 0;

  // repeated .tensorflow.TensorProto outputs = 2;
  {
    unsigned int count = this->outputs_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->outputs(i));
    }
  }

  // string status_msg = 5;
  if (this->status_msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->status_msg());
  }

  // bool is_output_dead = 1;
  if (this->is_output_dead() != 0) {
    total_size += 1 + 1;
  }

  // .tensorflow.error.Code status_code = 4;
  if (this->status_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->status_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TFOpContextUpdate::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:executor.TFOpContextUpdate)
  GOOGLE_DCHECK_NE(&from, this);
  const TFOpContextUpdate* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TFOpContextUpdate>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:executor.TFOpContextUpdate)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:executor.TFOpContextUpdate)
    MergeFrom(*source);
  }
}

void TFOpContextUpdate::MergeFrom(const TFOpContextUpdate& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:executor.TFOpContextUpdate)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  outputs_.MergeFrom(from.outputs_);
  if (from.status_msg().size() > 0) {

    status_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_msg_);
  }
  if (from.is_output_dead() != 0) {
    set_is_output_dead(from.is_output_dead());
  }
  if (from.status_code() != 0) {
    set_status_code(from.status_code());
  }
}

void TFOpContextUpdate::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:executor.TFOpContextUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TFOpContextUpdate::CopyFrom(const TFOpContextUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:executor.TFOpContextUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TFOpContextUpdate::IsInitialized() const {
  return true;
}

void TFOpContextUpdate::Swap(TFOpContextUpdate* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TFOpContextUpdate::InternalSwap(TFOpContextUpdate* other) {
  outputs_.UnsafeArenaSwap(&other->outputs_);
  status_msg_.Swap(&other->status_msg_);
  std::swap(is_output_dead_, other->is_output_dead_);
  std::swap(status_code_, other->status_code_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TFOpContextUpdate::GetMetadata() const {
  protobuf_tfoplibrary_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tfoplibrary_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TFOpContextUpdate

// bool is_output_dead = 1;
void TFOpContextUpdate::clear_is_output_dead() {
  is_output_dead_ = false;
}
bool TFOpContextUpdate::is_output_dead() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextUpdate.is_output_dead)
  return is_output_dead_;
}
void TFOpContextUpdate::set_is_output_dead(bool value) {
  
  is_output_dead_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextUpdate.is_output_dead)
}

// repeated .tensorflow.TensorProto outputs = 2;
int TFOpContextUpdate::outputs_size() const {
  return outputs_.size();
}
void TFOpContextUpdate::clear_outputs() {
  outputs_.Clear();
}
const ::tensorflow::TensorProto& TFOpContextUpdate::outputs(int index) const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextUpdate.outputs)
  return outputs_.Get(index);
}
::tensorflow::TensorProto* TFOpContextUpdate::mutable_outputs(int index) {
  // @@protoc_insertion_point(field_mutable:executor.TFOpContextUpdate.outputs)
  return outputs_.Mutable(index);
}
::tensorflow::TensorProto* TFOpContextUpdate::add_outputs() {
  // @@protoc_insertion_point(field_add:executor.TFOpContextUpdate.outputs)
  return outputs_.Add();
}
::google::protobuf::RepeatedPtrField< ::tensorflow::TensorProto >*
TFOpContextUpdate::mutable_outputs() {
  // @@protoc_insertion_point(field_mutable_list:executor.TFOpContextUpdate.outputs)
  return &outputs_;
}
const ::google::protobuf::RepeatedPtrField< ::tensorflow::TensorProto >&
TFOpContextUpdate::outputs() const {
  // @@protoc_insertion_point(field_list:executor.TFOpContextUpdate.outputs)
  return outputs_;
}

// .tensorflow.error.Code status_code = 4;
void TFOpContextUpdate::clear_status_code() {
  status_code_ = 0;
}
::tensorflow::error::Code TFOpContextUpdate::status_code() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextUpdate.status_code)
  return static_cast< ::tensorflow::error::Code >(status_code_);
}
void TFOpContextUpdate::set_status_code(::tensorflow::error::Code value) {
  
  status_code_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextUpdate.status_code)
}

// string status_msg = 5;
void TFOpContextUpdate::clear_status_msg() {
  status_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& TFOpContextUpdate::status_msg() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextUpdate.status_msg)
  return status_msg_.GetNoArena();
}
void TFOpContextUpdate::set_status_msg(const ::std::string& value) {
  
  status_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:executor.TFOpContextUpdate.status_msg)
}
#if LANG_CXX11
void TFOpContextUpdate::set_status_msg(::std::string&& value) {
  
  status_msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:executor.TFOpContextUpdate.status_msg)
}
#endif
void TFOpContextUpdate::set_status_msg(const char* value) {
  
  status_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:executor.TFOpContextUpdate.status_msg)
}
void TFOpContextUpdate::set_status_msg(const char* value, size_t size) {
  
  status_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:executor.TFOpContextUpdate.status_msg)
}
::std::string* TFOpContextUpdate::mutable_status_msg() {
  
  // @@protoc_insertion_point(field_mutable:executor.TFOpContextUpdate.status_msg)
  return status_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TFOpContextUpdate::release_status_msg() {
  // @@protoc_insertion_point(field_release:executor.TFOpContextUpdate.status_msg)
  
  return status_msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TFOpContextUpdate::set_allocated_status_msg(::std::string* status_msg) {
  if (status_msg != NULL) {
    
  } else {
    
  }
  status_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), status_msg);
  // @@protoc_insertion_point(field_set_allocated:executor.TFOpContextUpdate.status_msg)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace executor

// @@protoc_insertion_point(global_scope)
