// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tfoplibrary.proto

#ifndef PROTOBUF_tfoplibrary_2eproto__INCLUDED
#define PROTOBUF_tfoplibrary_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow/core/framework/node_def.pb.h"
#include "tensorflow/core/framework/function.pb.h"
#include "tensorflow/core/protobuf/config.pb.h"
// @@protoc_insertion_point(includes)
namespace executor {
class TFOpContextDef;
class TFOpContextDefDefaultTypeInternal;
extern TFOpContextDefDefaultTypeInternal _TFOpContextDef_default_instance_;
class TFOpKernelDef;
class TFOpKernelDefDefaultTypeInternal;
extern TFOpKernelDefDefaultTypeInternal _TFOpKernelDef_default_instance_;
}  // namespace executor
namespace tensorflow {
class ConfigProto;
class ConfigProtoDefaultTypeInternal;
extern ConfigProtoDefaultTypeInternal _ConfigProto_default_instance_;
class FunctionDef;
class FunctionDefDefaultTypeInternal;
extern FunctionDefDefaultTypeInternal _FunctionDef_default_instance_;
class FunctionDefLibrary;
class FunctionDefLibraryDefaultTypeInternal;
extern FunctionDefLibraryDefaultTypeInternal _FunctionDefLibrary_default_instance_;
class GPUOptions;
class GPUOptionsDefaultTypeInternal;
extern GPUOptionsDefaultTypeInternal _GPUOptions_default_instance_;
class GradientDef;
class GradientDefDefaultTypeInternal;
extern GradientDefDefaultTypeInternal _GradientDef_default_instance_;
class GraphOptions;
class GraphOptionsDefaultTypeInternal;
extern GraphOptionsDefaultTypeInternal _GraphOptions_default_instance_;
class NodeDef;
class NodeDefDefaultTypeInternal;
extern NodeDefDefaultTypeInternal _NodeDef_default_instance_;
class OptimizerOptions;
class OptimizerOptionsDefaultTypeInternal;
extern OptimizerOptionsDefaultTypeInternal _OptimizerOptions_default_instance_;
class RPCOptions;
class RPCOptionsDefaultTypeInternal;
extern RPCOptionsDefaultTypeInternal _RPCOptions_default_instance_;
class RunMetadata;
class RunMetadataDefaultTypeInternal;
extern RunMetadataDefaultTypeInternal _RunMetadata_default_instance_;
class RunOptions;
class RunOptionsDefaultTypeInternal;
extern RunOptionsDefaultTypeInternal _RunOptions_default_instance_;
class ThreadPoolOptionProto;
class ThreadPoolOptionProtoDefaultTypeInternal;
extern ThreadPoolOptionProtoDefaultTypeInternal _ThreadPoolOptionProto_default_instance_;
}  // namespace tensorflow

namespace executor {

namespace protobuf_tfoplibrary_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_tfoplibrary_2eproto

// ===================================================================

class TFOpKernelDef : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:executor.TFOpKernelDef) */ {
 public:
  TFOpKernelDef();
  virtual ~TFOpKernelDef();

  TFOpKernelDef(const TFOpKernelDef& from);

  inline TFOpKernelDef& operator=(const TFOpKernelDef& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TFOpKernelDef& default_instance();

  static inline const TFOpKernelDef* internal_default_instance() {
    return reinterpret_cast<const TFOpKernelDef*>(
               &_TFOpKernelDef_default_instance_);
  }

  void Swap(TFOpKernelDef* other);

  // implements Message ----------------------------------------------

  inline TFOpKernelDef* New() const PROTOBUF_FINAL { return New(NULL); }

  TFOpKernelDef* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TFOpKernelDef& from);
  void MergeFrom(const TFOpKernelDef& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TFOpKernelDef* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .tensorflow.NodeDef nodedef = 2;
  bool has_nodedef() const;
  void clear_nodedef();
  static const int kNodedefFieldNumber = 2;
  const ::tensorflow::NodeDef& nodedef() const;
  ::tensorflow::NodeDef* mutable_nodedef();
  ::tensorflow::NodeDef* release_nodedef();
  void set_allocated_nodedef(::tensorflow::NodeDef* nodedef);

  // .tensorflow.ConfigProto cfgProto = 3;
  bool has_cfgproto() const;
  void clear_cfgproto();
  static const int kCfgProtoFieldNumber = 3;
  const ::tensorflow::ConfigProto& cfgproto() const;
  ::tensorflow::ConfigProto* mutable_cfgproto();
  ::tensorflow::ConfigProto* release_cfgproto();
  void set_allocated_cfgproto(::tensorflow::ConfigProto* cfgproto);

  // .tensorflow.FunctionDefLibrary funcDef = 4;
  bool has_funcdef() const;
  void clear_funcdef();
  static const int kFuncDefFieldNumber = 4;
  const ::tensorflow::FunctionDefLibrary& funcdef() const;
  ::tensorflow::FunctionDefLibrary* mutable_funcdef();
  ::tensorflow::FunctionDefLibrary* release_funcdef();
  void set_allocated_funcdef(::tensorflow::FunctionDefLibrary* funcdef);

  // int32 graph_def_version = 1;
  void clear_graph_def_version();
  static const int kGraphDefVersionFieldNumber = 1;
  ::google::protobuf::int32 graph_def_version() const;
  void set_graph_def_version(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:executor.TFOpKernelDef)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::tensorflow::NodeDef* nodedef_;
  ::tensorflow::ConfigProto* cfgproto_;
  ::tensorflow::FunctionDefLibrary* funcdef_;
  ::google::protobuf::int32 graph_def_version_;
  mutable int _cached_size_;
  friend struct  protobuf_tfoplibrary_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TFOpContextDef : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:executor.TFOpContextDef) */ {
 public:
  TFOpContextDef();
  virtual ~TFOpContextDef();

  TFOpContextDef(const TFOpContextDef& from);

  inline TFOpContextDef& operator=(const TFOpContextDef& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TFOpContextDef& default_instance();

  static inline const TFOpContextDef* internal_default_instance() {
    return reinterpret_cast<const TFOpContextDef*>(
               &_TFOpContextDef_default_instance_);
  }

  void Swap(TFOpContextDef* other);

  // implements Message ----------------------------------------------

  inline TFOpContextDef* New() const PROTOBUF_FINAL { return New(NULL); }

  TFOpContextDef* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TFOpContextDef& from);
  void MergeFrom(const TFOpContextDef& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TFOpContextDef* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 host_persistent_alloc_ids = 3;
  int host_persistent_alloc_ids_size() const;
  void clear_host_persistent_alloc_ids();
  static const int kHostPersistentAllocIdsFieldNumber = 3;
  ::google::protobuf::int64 host_persistent_alloc_ids(int index) const;
  void set_host_persistent_alloc_ids(int index, ::google::protobuf::int64 value);
  void add_host_persistent_alloc_ids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      host_persistent_alloc_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_host_persistent_alloc_ids();

  // repeated int64 device_persistent_alloc_ids = 4;
  int device_persistent_alloc_ids_size() const;
  void clear_device_persistent_alloc_ids();
  static const int kDevicePersistentAllocIdsFieldNumber = 4;
  ::google::protobuf::int64 device_persistent_alloc_ids(int index) const;
  void set_device_persistent_alloc_ids(int index, ::google::protobuf::int64 value);
  void add_device_persistent_alloc_ids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      device_persistent_alloc_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_device_persistent_alloc_ids();

  // int64 host_temp_memory_size = 1;
  void clear_host_temp_memory_size();
  static const int kHostTempMemorySizeFieldNumber = 1;
  ::google::protobuf::int64 host_temp_memory_size() const;
  void set_host_temp_memory_size(::google::protobuf::int64 value);

  // int64 device_temp_memory_size = 2;
  void clear_device_temp_memory_size();
  static const int kDeviceTempMemorySizeFieldNumber = 2;
  ::google::protobuf::int64 device_temp_memory_size() const;
  void set_device_temp_memory_size(::google::protobuf::int64 value);

  // int64 host_persistent_memory_allocated = 5;
  void clear_host_persistent_memory_allocated();
  static const int kHostPersistentMemoryAllocatedFieldNumber = 5;
  ::google::protobuf::int64 host_persistent_memory_allocated() const;
  void set_host_persistent_memory_allocated(::google::protobuf::int64 value);

  // int64 device_persistent_memory_allocated = 6;
  void clear_device_persistent_memory_allocated();
  static const int kDevicePersistentMemoryAllocatedFieldNumber = 6;
  ::google::protobuf::int64 device_persistent_memory_allocated() const;
  void set_device_persistent_memory_allocated(::google::protobuf::int64 value);

  // bool is_output_dead = 7;
  void clear_is_output_dead();
  static const int kIsOutputDeadFieldNumber = 7;
  bool is_output_dead() const;
  void set_is_output_dead(bool value);

  // @@protoc_insertion_point(class_scope:executor.TFOpContextDef)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > host_persistent_alloc_ids_;
  mutable int _host_persistent_alloc_ids_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > device_persistent_alloc_ids_;
  mutable int _device_persistent_alloc_ids_cached_byte_size_;
  ::google::protobuf::int64 host_temp_memory_size_;
  ::google::protobuf::int64 device_temp_memory_size_;
  ::google::protobuf::int64 host_persistent_memory_allocated_;
  ::google::protobuf::int64 device_persistent_memory_allocated_;
  bool is_output_dead_;
  mutable int _cached_size_;
  friend struct  protobuf_tfoplibrary_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TFOpKernelDef

// int32 graph_def_version = 1;
inline void TFOpKernelDef::clear_graph_def_version() {
  graph_def_version_ = 0;
}
inline ::google::protobuf::int32 TFOpKernelDef::graph_def_version() const {
  // @@protoc_insertion_point(field_get:executor.TFOpKernelDef.graph_def_version)
  return graph_def_version_;
}
inline void TFOpKernelDef::set_graph_def_version(::google::protobuf::int32 value) {
  
  graph_def_version_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpKernelDef.graph_def_version)
}

// .tensorflow.NodeDef nodedef = 2;
inline bool TFOpKernelDef::has_nodedef() const {
  return this != internal_default_instance() && nodedef_ != NULL;
}
inline void TFOpKernelDef::clear_nodedef() {
  if (GetArenaNoVirtual() == NULL && nodedef_ != NULL) delete nodedef_;
  nodedef_ = NULL;
}
inline const ::tensorflow::NodeDef& TFOpKernelDef::nodedef() const {
  // @@protoc_insertion_point(field_get:executor.TFOpKernelDef.nodedef)
  return nodedef_ != NULL ? *nodedef_
                         : *::tensorflow::NodeDef::internal_default_instance();
}
inline ::tensorflow::NodeDef* TFOpKernelDef::mutable_nodedef() {
  
  if (nodedef_ == NULL) {
    nodedef_ = new ::tensorflow::NodeDef;
  }
  // @@protoc_insertion_point(field_mutable:executor.TFOpKernelDef.nodedef)
  return nodedef_;
}
inline ::tensorflow::NodeDef* TFOpKernelDef::release_nodedef() {
  // @@protoc_insertion_point(field_release:executor.TFOpKernelDef.nodedef)
  
  ::tensorflow::NodeDef* temp = nodedef_;
  nodedef_ = NULL;
  return temp;
}
inline void TFOpKernelDef::set_allocated_nodedef(::tensorflow::NodeDef* nodedef) {
  delete nodedef_;
  if (nodedef != NULL && nodedef->GetArena() != NULL) {
    ::tensorflow::NodeDef* new_nodedef = new ::tensorflow::NodeDef;
    new_nodedef->CopyFrom(*nodedef);
    nodedef = new_nodedef;
  }
  nodedef_ = nodedef;
  if (nodedef) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:executor.TFOpKernelDef.nodedef)
}

// .tensorflow.ConfigProto cfgProto = 3;
inline bool TFOpKernelDef::has_cfgproto() const {
  return this != internal_default_instance() && cfgproto_ != NULL;
}
inline void TFOpKernelDef::clear_cfgproto() {
  if (GetArenaNoVirtual() == NULL && cfgproto_ != NULL) delete cfgproto_;
  cfgproto_ = NULL;
}
inline const ::tensorflow::ConfigProto& TFOpKernelDef::cfgproto() const {
  // @@protoc_insertion_point(field_get:executor.TFOpKernelDef.cfgProto)
  return cfgproto_ != NULL ? *cfgproto_
                         : *::tensorflow::ConfigProto::internal_default_instance();
}
inline ::tensorflow::ConfigProto* TFOpKernelDef::mutable_cfgproto() {
  
  if (cfgproto_ == NULL) {
    cfgproto_ = new ::tensorflow::ConfigProto;
  }
  // @@protoc_insertion_point(field_mutable:executor.TFOpKernelDef.cfgProto)
  return cfgproto_;
}
inline ::tensorflow::ConfigProto* TFOpKernelDef::release_cfgproto() {
  // @@protoc_insertion_point(field_release:executor.TFOpKernelDef.cfgProto)
  
  ::tensorflow::ConfigProto* temp = cfgproto_;
  cfgproto_ = NULL;
  return temp;
}
inline void TFOpKernelDef::set_allocated_cfgproto(::tensorflow::ConfigProto* cfgproto) {
  delete cfgproto_;
  if (cfgproto != NULL && cfgproto->GetArena() != NULL) {
    ::tensorflow::ConfigProto* new_cfgproto = new ::tensorflow::ConfigProto;
    new_cfgproto->CopyFrom(*cfgproto);
    cfgproto = new_cfgproto;
  }
  cfgproto_ = cfgproto;
  if (cfgproto) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:executor.TFOpKernelDef.cfgProto)
}

// .tensorflow.FunctionDefLibrary funcDef = 4;
inline bool TFOpKernelDef::has_funcdef() const {
  return this != internal_default_instance() && funcdef_ != NULL;
}
inline void TFOpKernelDef::clear_funcdef() {
  if (GetArenaNoVirtual() == NULL && funcdef_ != NULL) delete funcdef_;
  funcdef_ = NULL;
}
inline const ::tensorflow::FunctionDefLibrary& TFOpKernelDef::funcdef() const {
  // @@protoc_insertion_point(field_get:executor.TFOpKernelDef.funcDef)
  return funcdef_ != NULL ? *funcdef_
                         : *::tensorflow::FunctionDefLibrary::internal_default_instance();
}
inline ::tensorflow::FunctionDefLibrary* TFOpKernelDef::mutable_funcdef() {
  
  if (funcdef_ == NULL) {
    funcdef_ = new ::tensorflow::FunctionDefLibrary;
  }
  // @@protoc_insertion_point(field_mutable:executor.TFOpKernelDef.funcDef)
  return funcdef_;
}
inline ::tensorflow::FunctionDefLibrary* TFOpKernelDef::release_funcdef() {
  // @@protoc_insertion_point(field_release:executor.TFOpKernelDef.funcDef)
  
  ::tensorflow::FunctionDefLibrary* temp = funcdef_;
  funcdef_ = NULL;
  return temp;
}
inline void TFOpKernelDef::set_allocated_funcdef(::tensorflow::FunctionDefLibrary* funcdef) {
  delete funcdef_;
  if (funcdef != NULL && funcdef->GetArena() != NULL) {
    ::tensorflow::FunctionDefLibrary* new_funcdef = new ::tensorflow::FunctionDefLibrary;
    new_funcdef->CopyFrom(*funcdef);
    funcdef = new_funcdef;
  }
  funcdef_ = funcdef;
  if (funcdef) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:executor.TFOpKernelDef.funcDef)
}

// -------------------------------------------------------------------

// TFOpContextDef

// int64 host_temp_memory_size = 1;
inline void TFOpContextDef::clear_host_temp_memory_size() {
  host_temp_memory_size_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 TFOpContextDef::host_temp_memory_size() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.host_temp_memory_size)
  return host_temp_memory_size_;
}
inline void TFOpContextDef::set_host_temp_memory_size(::google::protobuf::int64 value) {
  
  host_temp_memory_size_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.host_temp_memory_size)
}

// int64 device_temp_memory_size = 2;
inline void TFOpContextDef::clear_device_temp_memory_size() {
  device_temp_memory_size_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 TFOpContextDef::device_temp_memory_size() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.device_temp_memory_size)
  return device_temp_memory_size_;
}
inline void TFOpContextDef::set_device_temp_memory_size(::google::protobuf::int64 value) {
  
  device_temp_memory_size_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.device_temp_memory_size)
}

// repeated int64 host_persistent_alloc_ids = 3;
inline int TFOpContextDef::host_persistent_alloc_ids_size() const {
  return host_persistent_alloc_ids_.size();
}
inline void TFOpContextDef::clear_host_persistent_alloc_ids() {
  host_persistent_alloc_ids_.Clear();
}
inline ::google::protobuf::int64 TFOpContextDef::host_persistent_alloc_ids(int index) const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.host_persistent_alloc_ids)
  return host_persistent_alloc_ids_.Get(index);
}
inline void TFOpContextDef::set_host_persistent_alloc_ids(int index, ::google::protobuf::int64 value) {
  host_persistent_alloc_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.host_persistent_alloc_ids)
}
inline void TFOpContextDef::add_host_persistent_alloc_ids(::google::protobuf::int64 value) {
  host_persistent_alloc_ids_.Add(value);
  // @@protoc_insertion_point(field_add:executor.TFOpContextDef.host_persistent_alloc_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
TFOpContextDef::host_persistent_alloc_ids() const {
  // @@protoc_insertion_point(field_list:executor.TFOpContextDef.host_persistent_alloc_ids)
  return host_persistent_alloc_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
TFOpContextDef::mutable_host_persistent_alloc_ids() {
  // @@protoc_insertion_point(field_mutable_list:executor.TFOpContextDef.host_persistent_alloc_ids)
  return &host_persistent_alloc_ids_;
}

// repeated int64 device_persistent_alloc_ids = 4;
inline int TFOpContextDef::device_persistent_alloc_ids_size() const {
  return device_persistent_alloc_ids_.size();
}
inline void TFOpContextDef::clear_device_persistent_alloc_ids() {
  device_persistent_alloc_ids_.Clear();
}
inline ::google::protobuf::int64 TFOpContextDef::device_persistent_alloc_ids(int index) const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.device_persistent_alloc_ids)
  return device_persistent_alloc_ids_.Get(index);
}
inline void TFOpContextDef::set_device_persistent_alloc_ids(int index, ::google::protobuf::int64 value) {
  device_persistent_alloc_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.device_persistent_alloc_ids)
}
inline void TFOpContextDef::add_device_persistent_alloc_ids(::google::protobuf::int64 value) {
  device_persistent_alloc_ids_.Add(value);
  // @@protoc_insertion_point(field_add:executor.TFOpContextDef.device_persistent_alloc_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
TFOpContextDef::device_persistent_alloc_ids() const {
  // @@protoc_insertion_point(field_list:executor.TFOpContextDef.device_persistent_alloc_ids)
  return device_persistent_alloc_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
TFOpContextDef::mutable_device_persistent_alloc_ids() {
  // @@protoc_insertion_point(field_mutable_list:executor.TFOpContextDef.device_persistent_alloc_ids)
  return &device_persistent_alloc_ids_;
}

// int64 host_persistent_memory_allocated = 5;
inline void TFOpContextDef::clear_host_persistent_memory_allocated() {
  host_persistent_memory_allocated_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 TFOpContextDef::host_persistent_memory_allocated() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.host_persistent_memory_allocated)
  return host_persistent_memory_allocated_;
}
inline void TFOpContextDef::set_host_persistent_memory_allocated(::google::protobuf::int64 value) {
  
  host_persistent_memory_allocated_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.host_persistent_memory_allocated)
}

// int64 device_persistent_memory_allocated = 6;
inline void TFOpContextDef::clear_device_persistent_memory_allocated() {
  device_persistent_memory_allocated_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 TFOpContextDef::device_persistent_memory_allocated() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.device_persistent_memory_allocated)
  return device_persistent_memory_allocated_;
}
inline void TFOpContextDef::set_device_persistent_memory_allocated(::google::protobuf::int64 value) {
  
  device_persistent_memory_allocated_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.device_persistent_memory_allocated)
}

// bool is_output_dead = 7;
inline void TFOpContextDef::clear_is_output_dead() {
  is_output_dead_ = false;
}
inline bool TFOpContextDef::is_output_dead() const {
  // @@protoc_insertion_point(field_get:executor.TFOpContextDef.is_output_dead)
  return is_output_dead_;
}
inline void TFOpContextDef::set_is_output_dead(bool value) {
  
  is_output_dead_ = value;
  // @@protoc_insertion_point(field_set:executor.TFOpContextDef.is_output_dead)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace executor

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tfoplibrary_2eproto__INCLUDED
